id: f483abc0a4184384b7879b42486a1c92
initial_creation_type: ocr
source_metadata:
  volumes:
    4776e7818ad34bcd92ff36fe4310d62c:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
